---
# file: oracle-java/tasks/check_environment.yml
#
# task to set host facts:
#   - Java is installed?
#   - which Java version is installed?
#   - is ansible version correct ?
#

- name: determine if Java is already installed
  shell: which java
  register: oracle_java_task_installed
  changed_when: oracle_java_task_installed.rc != 0
  failed_when: no
# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed

- name: set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ not oracle_java_task_installed.changed }}

- name: determine which Java version is installed
  shell: java -version
  when: oracle_java_installed
  register: oracle_java_task_version
  changed_when: False

- name: set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed="{{ oracle_java_task_version.stderr.split('\n')[0]|regex_replace('.*\"(.*)\"','\\1') }}"
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False

- debug:
    var="{{ item }}"
  when: item is defined and debug | default(false)
  with_items:
    - oracle_java_installed
    - oracle_java_task_installed
    - oracle_java_task_version
    - oracle_java_version_installed
    - oracle_java_version_string

  # prior to 2.4, ansible facts for linux mint are:
  # "ansible_os_family": "Linuxmint"
  # "ansible_distribution": "Linuxmint"
  # after 2.4, the facts change to something more sane
  # "ansible_os_family": "Debian"
  # "ansible_distribution": "Linux Mint"
- name: check ansible version
  when: ansible_distribution == 'Linux Mint' or ansible_distribution == 'Linuxmint'
  assert:
    that: "ansible_version.full | version_compare('2.4', '>=')"
    msg: "You must update Ansible to at least 2.4 to use this role with Linux Mint"
