---
# file: oracle-java/tasks/debian/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Debian based Linux distribution.
#

- name: add java ppa repo
  apt_repository: repo=ppa:webupd8team/java state=present update_cache=yes
  when: "{{ ansible_distribution == 'Ubuntu' }}"
  
- block:
  - name: ensure the webupd8 launchpad apt repository key is present
    apt_key:
      id=0xC2518248EEA14886
      keyserver=keyserver.ubuntu.com
      state=present

  - name: ensure the webupd8 launchpad apt repository is present
    apt_repository:
      repo='{{ item }} http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
      update_cache=yes
      state=present
    with_items:
      - deb
      - deb-src
  when: "{{ ansible_distribution == 'Debian' }}"
  
- name: Check if oracle license is already accepted
  shell: debconf-get-selections |grep "oracle-java{{ oracle_java_version }}-installer\sshared/accepted-oracle-license-v1-1\sboolean\strue"
  register: licence_not_accepted
  failed_when: false
  changed_when: licence_not_accepted.rc != 0
  when: "{{ ansible_distribution == 'Ubuntu' }}"

- name: Set license as accepted
  debconf: name='oracle-java{{ oracle_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: "{{ licence_not_accepted|changed or licence_not_accepted|skipped }}"

- name: ensure Java is installed
  apt:
    name="oracle-java{{ oracle_java_version }}-installer"
    state={{ oracle_java_state }}
    cache_valid_time={{ oracle_java_cache_valid_time }}
    update_cache=yes
  register: oracle_java_task_apt_install
  become: yes

- name: set Java version as default
  apt:
    name="oracle-java{{ oracle_java_version }}-set-default"
    state=latest
  register: oracle_java_task_set_default
  when: oracle_java_set_as_default
  become: yes

- name: in case there were changes, check host environment again
  include: ../check_environment.yml
  when: oracle_java_task_apt_install|changed or oracle_java_task_set_default|changed
